version: "3.3"
services:
  back-balancer:
    build: ./../loadbalancer/backend/
    ports:
      - "5000:80"
    depends_on:
      - back1
      - back2
      - back3
      - back4
      - back5
      - back6
  back1:
    build: ./
    ports:
      - "5001:5000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Meylin123*"
      DATABASE_OPTION_DATABASE: "todos"
      API_PORT: "5000"
      SERVER_TAG: "BACK1"
    depends_on:
      - basededatos
    links:
      - "basededatos"
  back2:
    build: ./
    ports:
      - "5002:5000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Meylin123*"
      DATABASE_OPTION_DATABASE: "todos"
      API_PORT: "5000"
      SERVER_TAG: "BACK2"
    depends_on:
      - basededatos
    links:
      - "basededatos"
  back3:
    build: ./
    ports:
      - "5003:5000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Meylin123*"
      DATABASE_OPTION_DATABASE: "todos"
      API_PORT: "5000"
      SERVER_TAG: "BACK3"
    depends_on:
      - basededatos
    links:
      - "basededatos"
  back4:
    build: ./
    ports:
      - "5004:5000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Meylin123*"
      DATABASE_OPTION_DATABASE: "todos"
      API_PORT: "5000"
      SERVER_TAG: "BACK4"
    depends_on:
      - basededatos
    links:
      - "basededatos"
  back5:
    build: ./
    ports:
      - "5005:5000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Meylin123*"
      DATABASE_OPTION_DATABASE: "todos"
      API_PORT: "5000"
      SERVER_TAG: "BACK5"
    depends_on:
      - basededatos
    links:
      - "basededatos"
  back6:
    build: ./
    ports:
      - "5006:5000"
    environment:
      DATABASE_SERVER: "sqlserver"
      DATABASE_AUTHENTICATION_TYPE: "default"
      DATABASE_AUTHENTICATION_USERNAME: "sa"
      DATABASE_AUTHENTICATION_PASSWORD: "Meylin123*"
      DATABASE_OPTION_DATABASE: "todos"
      API_PORT: "5000"
      SERVER_TAG: "BACK6"
    depends_on:
      - basededatos
    links:
      - "basededatos"
  basededatos:
    image: "mcr.microsoft.com/mssql/server"
    user: "0:0"
    hostname: "sqlserver"
    environment:
      SA_PASSWORD: "Meylin123*"
      ACCEPT_EULA: "Y"
    volumes:
      - datos:/var/opt/mssql/data
volumes:
  datos:
